---
title: "Kerbros:IP Configuration"
description: "Get IP Configuration of windows machine using kerbros"

flintbit: "flint-util:winrm:kerbros:ipconfig.rb"
icon: "fa fa-globe"
inputs:
  -
    section: Get IP Configuration of Windows Machine
    fields:
      -
        default:
        id: hostname
        label: Hostname
        placeholder: "Enter hostname"
        type: hostname
        required: true
      -
        default:
        id: username
        label: Username
        placeholder: "Enter username"
        type: textbox
        required: true
      -
        default:
        id: kerb5_realm
        label: Kerbros5 realm
        placeholder: "Kerbros5 realm"
        type: textbox
        required: true
      -
        default:
        id: protocol
        label: Protocol
        placeholder: "Http/Https"
        type: select
        required: true
        options:
          - "http"
          - "https"
...
